import numpy


numpy.testing.assert_raises(ValueError, callable)